-- =============================================================
-- Restaurant Recommendation System - Oracle SQL Schema
-- =============================================================

-- Drop tables if they exist (for clean re-run)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ADMIN_INVITES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE UPDATE_REQUESTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE EVENTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE FAVORITES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE REVIEWS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RESTAURANT_CUISINE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CUISINES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE RESTAURANTS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE USERS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Drop sequences
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_USER_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_RESTAURANT_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_REVIEW_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CUISINE_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_FAVORITE_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_REQUEST_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EVENT_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_INVITE_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- =============================================================
-- SEQUENCES
-- =============================================================
CREATE SEQUENCE SEQ_USER_ID       START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RESTAURANT_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_REVIEW_ID     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CUISINE_ID    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_FAVORITE_ID   START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_REQUEST_ID    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_EVENT_ID      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_INVITE_ID     START WITH 1 INCREMENT BY 1 NOCACHE;

-- =============================================================
-- TABLE: USERS
-- =============================================================
CREATE TABLE USERS (
  USER_ID        NUMBER        DEFAULT SEQ_USER_ID.NEXTVAL  PRIMARY KEY,
  USERNAME       VARCHAR2(50)  NOT NULL,
  EMAIL          VARCHAR2(100) NOT NULL,
  PASSWORD_HASH  VARCHAR2(255) NOT NULL,
  ROLE           VARCHAR2(20)  DEFAULT 'USER' NOT NULL,
  LICENSE_NUMBER VARCHAR2(100),
  STATUS         VARCHAR2(20)  DEFAULT 'APPROVED' NOT NULL,
  CREATED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT UQ_USERS_EMAIL    UNIQUE (EMAIL),
  CONSTRAINT UQ_USERS_USERNAME UNIQUE (USERNAME),
  CONSTRAINT CHK_USERS_ROLE    CHECK (ROLE IN ('USER', 'OWNER', 'ADMIN')),
  CONSTRAINT CHK_USERS_STATUS  CHECK (STATUS IN ('PENDING', 'APPROVED', 'REJECTED'))
);

COMMENT ON TABLE  USERS               IS 'Application users (normal users, owners, admins)';
COMMENT ON COLUMN USERS.ROLE          IS 'USER = regular user, OWNER = restaurant owner, ADMIN = administrator';
COMMENT ON COLUMN USERS.LICENSE_NUMBER IS 'Business license number, required for OWNER accounts';
COMMENT ON COLUMN USERS.STATUS        IS 'PENDING = awaiting admin approval (owners), APPROVED = active, REJECTED = denied';

-- =============================================================
-- TABLE: RESTAURANTS
-- =============================================================
CREATE TABLE RESTAURANTS (
  RESTAURANT_ID NUMBER        DEFAULT SEQ_RESTAURANT_ID.NEXTVAL PRIMARY KEY,
  NAME          VARCHAR2(150) NOT NULL,
  LATITUDE      NUMBER(10,7)  NOT NULL,
  LONGITUDE     NUMBER(10,7)  NOT NULL,
  ADDRESS       VARCHAR2(300) NOT NULL,
  PRICE_RANGE   VARCHAR2(10)  DEFAULT '$$',
  PHONE         VARCHAR2(20),
  WEBSITE       VARCHAR2(255),
  STATUS        VARCHAR2(20)  DEFAULT 'PENDING' NOT NULL,
  ADDED_BY      NUMBER,
  CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT CHK_REST_PRICE  CHECK (PRICE_RANGE IN ('$', '$$', '$$$', '$$$$')),
  CONSTRAINT CHK_REST_STATUS CHECK (STATUS IN ('PENDING', 'APPROVED', 'REJECTED')),
  CONSTRAINT CHK_REST_LAT    CHECK (LATITUDE  BETWEEN -90  AND 90),
  CONSTRAINT CHK_REST_LNG    CHECK (LONGITUDE BETWEEN -180 AND 180),
  CONSTRAINT FK_REST_USER    FOREIGN KEY (ADDED_BY) REFERENCES USERS(USER_ID) ON DELETE SET NULL
);

COMMENT ON TABLE  RESTAURANTS          IS 'Restaurant listings';
COMMENT ON COLUMN RESTAURANTS.STATUS   IS 'PENDING = awaiting admin review, APPROVED = visible, REJECTED = removed';
COMMENT ON COLUMN RESTAURANTS.LATITUDE IS 'GPS latitude for map display';

-- =============================================================
-- TABLE: CUISINES
-- =============================================================
CREATE TABLE CUISINES (
  CUISINE_ID NUMBER        DEFAULT SEQ_CUISINE_ID.NEXTVAL PRIMARY KEY,
  NAME       VARCHAR2(100) NOT NULL,
  CONSTRAINT UQ_CUISINE_NAME UNIQUE (NAME)
);

-- =============================================================
-- TABLE: RESTAURANT_CUISINE (junction)
-- =============================================================
CREATE TABLE RESTAURANT_CUISINE (
  RESTAURANT_ID NUMBER NOT NULL,
  CUISINE_ID    NUMBER NOT NULL,
  CONSTRAINT PK_REST_CUI    PRIMARY KEY (RESTAURANT_ID, CUISINE_ID),
  CONSTRAINT FK_RC_REST     FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS(RESTAURANT_ID) ON DELETE CASCADE,
  CONSTRAINT FK_RC_CUISINE  FOREIGN KEY (CUISINE_ID)    REFERENCES CUISINES(CUISINE_ID)    ON DELETE CASCADE
);

-- =============================================================
-- TABLE: REVIEWS
-- =============================================================
CREATE TABLE REVIEWS (
  REVIEW_ID     NUMBER        DEFAULT SEQ_REVIEW_ID.NEXTVAL PRIMARY KEY,
  RESTAURANT_ID NUMBER        NOT NULL,
  USER_ID       NUMBER        NOT NULL,
  RATING        NUMBER(2,1)   NOT NULL,
  REVIEW_TEXT   VARCHAR2(2000),
  STATUS        VARCHAR2(20)  DEFAULT 'APPROVED' NOT NULL,
  CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT UQ_REVIEW_USER_REST UNIQUE (RESTAURANT_ID, USER_ID),
  CONSTRAINT CHK_RATING          CHECK (RATING BETWEEN 1 AND 5),
  CONSTRAINT CHK_REVIEW_STATUS   CHECK (STATUS IN ('PENDING', 'APPROVED', 'REJECTED')),
  CONSTRAINT FK_REV_REST         FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS(RESTAURANT_ID) ON DELETE CASCADE,
  CONSTRAINT FK_REV_USER         FOREIGN KEY (USER_ID)       REFERENCES USERS(USER_ID)       ON DELETE CASCADE
);

COMMENT ON COLUMN REVIEWS.RATING IS 'Rating between 1.0 and 5.0';

-- =============================================================
-- TABLE: FAVORITES
-- =============================================================
CREATE TABLE FAVORITES (
  FAVORITE_ID   NUMBER    DEFAULT SEQ_FAVORITE_ID.NEXTVAL PRIMARY KEY,
  USER_ID       NUMBER    NOT NULL,
  RESTAURANT_ID NUMBER    NOT NULL,
  ADDED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT UQ_FAV_USER_REST UNIQUE (USER_ID, RESTAURANT_ID),
  CONSTRAINT FK_FAV_USER      FOREIGN KEY (USER_ID)       REFERENCES USERS(USER_ID)       ON DELETE CASCADE,
  CONSTRAINT FK_FAV_REST      FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS(RESTAURANT_ID) ON DELETE CASCADE
);

-- =============================================================
-- TABLE: UPDATE_REQUESTS
-- =============================================================
CREATE TABLE UPDATE_REQUESTS (
  REQUEST_ID    NUMBER         DEFAULT SEQ_REQUEST_ID.NEXTVAL PRIMARY KEY,
  RESTAURANT_ID NUMBER         NOT NULL,
  OWNER_ID      NUMBER         NOT NULL,
  FIELD_NAME    VARCHAR2(50)   NOT NULL,
  OLD_VALUE     VARCHAR2(500),
  NEW_VALUE     VARCHAR2(500),
  STATUS        VARCHAR2(20)   DEFAULT 'PENDING' NOT NULL,
  CREATED_AT    TIMESTAMP      DEFAULT SYSTIMESTAMP,
  CONSTRAINT CHK_UREQ_STATUS  CHECK (STATUS IN ('PENDING', 'APPROVED', 'REJECTED')),
  CONSTRAINT FK_UREQ_REST     FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS(RESTAURANT_ID) ON DELETE CASCADE,
  CONSTRAINT FK_UREQ_OWNER    FOREIGN KEY (OWNER_ID)      REFERENCES USERS(USER_ID)       ON DELETE CASCADE
);

COMMENT ON TABLE UPDATE_REQUESTS IS 'Owner-submitted restaurant edit requests pending admin approval';

-- =============================================================
-- TABLE: EVENTS
-- =============================================================
CREATE TABLE EVENTS (
  EVENT_ID      NUMBER         DEFAULT SEQ_EVENT_ID.NEXTVAL PRIMARY KEY,
  RESTAURANT_ID NUMBER         NOT NULL,
  OWNER_ID      NUMBER         NOT NULL,
  EVENT_NAME    VARCHAR2(200)  NOT NULL,
  DESCRIPTION   VARCHAR2(1000),
  EVENT_DATE    DATE           NOT NULL,
  STATUS        VARCHAR2(20)   DEFAULT 'UPCOMING' NOT NULL,
  CREATED_AT    TIMESTAMP      DEFAULT SYSTIMESTAMP,
  CONSTRAINT CHK_EVT_STATUS   CHECK (STATUS IN ('UPCOMING', 'ONGOING', 'COMPLETED', 'CANCELLED')),
  CONSTRAINT FK_EVT_REST      FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS(RESTAURANT_ID) ON DELETE CASCADE,
  CONSTRAINT FK_EVT_OWNER     FOREIGN KEY (OWNER_ID)      REFERENCES USERS(USER_ID)       ON DELETE CASCADE
);

COMMENT ON TABLE EVENTS IS 'Restaurant-hosted events (created by owners, no admin approval needed)';

-- =============================================================
-- TABLE: ADMIN_INVITES
-- =============================================================
CREATE TABLE ADMIN_INVITES (
  INVITE_ID     NUMBER         DEFAULT SEQ_INVITE_ID.NEXTVAL PRIMARY KEY,
  INVITEE_ID    NUMBER         NOT NULL,
  INVITED_BY    NUMBER         NOT NULL,
  STATUS        VARCHAR2(20)   DEFAULT 'PENDING' NOT NULL,
  CREATED_AT    TIMESTAMP      DEFAULT SYSTIMESTAMP,
  CONSTRAINT UQ_INVITE_USER   UNIQUE (INVITEE_ID, STATUS),
  CONSTRAINT CHK_INV_STATUS   CHECK (STATUS IN ('PENDING', 'ACCEPTED', 'DECLINED')),
  CONSTRAINT FK_INV_INVITEE   FOREIGN KEY (INVITEE_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
  CONSTRAINT FK_INV_BY        FOREIGN KEY (INVITED_BY) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

COMMENT ON TABLE ADMIN_INVITES IS 'Invitations sent by admins to promote regular users to admin role';

-- =============================================================
-- INDEXES for performance
-- =============================================================
CREATE INDEX IDX_REST_STATUS   ON RESTAURANTS(STATUS);
CREATE INDEX IDX_REST_LOCATION ON RESTAURANTS(LATITUDE, LONGITUDE);
CREATE INDEX IDX_REVIEWS_REST  ON REVIEWS(RESTAURANT_ID);
CREATE INDEX IDX_FAV_USER      ON FAVORITES(USER_ID);
CREATE INDEX IDX_UREQ_STATUS   ON UPDATE_REQUESTS(STATUS);
CREATE INDEX IDX_EVT_REST      ON EVENTS(RESTAURANT_ID);
CREATE INDEX IDX_EVT_DATE      ON EVENTS(EVENT_DATE);
CREATE INDEX IDX_INV_INVITEE   ON ADMIN_INVITES(INVITEE_ID);
CREATE INDEX IDX_USER_STATUS   ON USERS(STATUS);

-- =============================================================
-- TRIGGERS: Auto-set IDs from sequence
-- =============================================================
CREATE OR REPLACE TRIGGER TRG_USERS_ID
BEFORE INSERT ON USERS
FOR EACH ROW
WHEN (NEW.USER_ID IS NULL)
BEGIN
  SELECT SEQ_USER_ID.NEXTVAL INTO :NEW.USER_ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_RESTAURANTS_ID
BEFORE INSERT ON RESTAURANTS
FOR EACH ROW
WHEN (NEW.RESTAURANT_ID IS NULL)
BEGIN
  SELECT SEQ_RESTAURANT_ID.NEXTVAL INTO :NEW.RESTAURANT_ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_REVIEWS_ID
BEFORE INSERT ON REVIEWS
FOR EACH ROW
WHEN (NEW.REVIEW_ID IS NULL)
BEGIN
  SELECT SEQ_REVIEW_ID.NEXTVAL INTO :NEW.REVIEW_ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_CUISINES_ID
BEFORE INSERT ON CUISINES
FOR EACH ROW
WHEN (NEW.CUISINE_ID IS NULL)
BEGIN
  SELECT SEQ_CUISINE_ID.NEXTVAL INTO :NEW.CUISINE_ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_FAVORITES_ID
BEFORE INSERT ON FAVORITES
FOR EACH ROW
WHEN (NEW.FAVORITE_ID IS NULL)
BEGIN
  SELECT SEQ_FAVORITE_ID.NEXTVAL INTO :NEW.FAVORITE_ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_REQUESTS_ID
BEFORE INSERT ON UPDATE_REQUESTS
FOR EACH ROW
WHEN (NEW.REQUEST_ID IS NULL)
BEGIN
  SELECT SEQ_REQUEST_ID.NEXTVAL INTO :NEW.REQUEST_ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_EVENTS_ID
BEFORE INSERT ON EVENTS
FOR EACH ROW
WHEN (NEW.EVENT_ID IS NULL)
BEGIN
  SELECT SEQ_EVENT_ID.NEXTVAL INTO :NEW.EVENT_ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_INVITES_ID
BEFORE INSERT ON ADMIN_INVITES
FOR EACH ROW
WHEN (NEW.INVITE_ID IS NULL)
BEGIN
  SELECT SEQ_INVITE_ID.NEXTVAL INTO :NEW.INVITE_ID FROM DUAL;
END;
/

-- =============================================================

SELECT TABLE_NAME FROM USER_TABLES ORDER BY TABLE_NAME;
