-- =============================================================
-- Restaurant Recommendation System - Oracle SQL Schema
-- =============================================================

-- Drop tables if they exist (for clean re-run)
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FAVORITES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE REVIEWS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESTAURANT_CUISINE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CUISINES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE RESTAURANTS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE USERS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Drop sequences
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_USER_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_RESTAURANT_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_REVIEW_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CUISINE_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_FAVORITE_ID'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- =============================================================
-- SEQUENCES
-- =============================================================
CREATE SEQUENCE SEQ_USER_ID       START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RESTAURANT_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_REVIEW_ID     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CUISINE_ID    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_FAVORITE_ID   START WITH 1 INCREMENT BY 1 NOCACHE;

-- =============================================================
-- TABLE: USERS
-- =============================================================
CREATE TABLE USERS (
  USER_ID       NUMBER        DEFAULT SEQ_USER_ID.NEXTVAL  PRIMARY KEY,
  USERNAME      VARCHAR2(50)  NOT NULL,
  EMAIL         VARCHAR2(100) NOT NULL,
  PASSWORD_HASH VARCHAR2(255) NOT NULL,
  ROLE          VARCHAR2(20)  DEFAULT 'USER' NOT NULL,
  CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT UQ_USERS_EMAIL    UNIQUE (EMAIL),
  CONSTRAINT UQ_USERS_USERNAME UNIQUE (USERNAME),
  CONSTRAINT CHK_USERS_ROLE    CHECK (ROLE IN ('USER', 'ADMIN'))
);

COMMENT ON TABLE  USERS             IS 'Application users (normal users and admins)';
COMMENT ON COLUMN USERS.ROLE        IS 'USER = regular user, ADMIN = administrator';
COMMENT ON COLUMN USERS.PASSWORD_HASH IS 'SHA-256 hash of the password';

-- =============================================================
-- TABLE: RESTAURANTS
-- =============================================================
CREATE TABLE RESTAURANTS (
  RESTAURANT_ID NUMBER        DEFAULT SEQ_RESTAURANT_ID.NEXTVAL PRIMARY KEY,
  NAME          VARCHAR2(150) NOT NULL,
  LATITUDE      NUMBER(10,7)  NOT NULL,
  LONGITUDE     NUMBER(10,7)  NOT NULL,
  ADDRESS       VARCHAR2(300) NOT NULL,
  PRICE_RANGE   VARCHAR2(10)  DEFAULT '$$',
  PHONE         VARCHAR2(20),
  WEBSITE       VARCHAR2(255),
  STATUS        VARCHAR2(20)  DEFAULT 'PENDING' NOT NULL,
  ADDED_BY      NUMBER,
  CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT CHK_REST_PRICE  CHECK (PRICE_RANGE IN ('$', '$$', '$$$', '$$$$')),
  CONSTRAINT CHK_REST_STATUS CHECK (STATUS IN ('PENDING', 'APPROVED', 'REJECTED')),
  CONSTRAINT CHK_REST_LAT    CHECK (LATITUDE  BETWEEN -90  AND 90),
  CONSTRAINT CHK_REST_LNG    CHECK (LONGITUDE BETWEEN -180 AND 180),
  CONSTRAINT FK_REST_USER    FOREIGN KEY (ADDED_BY) REFERENCES USERS(USER_ID) ON DELETE SET NULL
);

COMMENT ON TABLE  RESTAURANTS          IS 'Restaurant listings';
COMMENT ON COLUMN RESTAURANTS.STATUS   IS 'PENDING = awaiting admin review, APPROVED = visible, REJECTED = removed';
COMMENT ON COLUMN RESTAURANTS.LATITUDE IS 'GPS latitude for map display';

-- =============================================================
-- TABLE: CUISINES
-- =============================================================
CREATE TABLE CUISINES (
  CUISINE_ID NUMBER        DEFAULT SEQ_CUISINE_ID.NEXTVAL PRIMARY KEY,
  NAME       VARCHAR2(100) NOT NULL,
  CONSTRAINT UQ_CUISINE_NAME UNIQUE (NAME)
);

-- =============================================================
-- TABLE: RESTAURANT_CUISINE (junction)
-- =============================================================
CREATE TABLE RESTAURANT_CUISINE (
  RESTAURANT_ID NUMBER NOT NULL,
  CUISINE_ID    NUMBER NOT NULL,
  CONSTRAINT PK_REST_CUI    PRIMARY KEY (RESTAURANT_ID, CUISINE_ID),
  CONSTRAINT FK_RC_REST     FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS(RESTAURANT_ID) ON DELETE CASCADE,
  CONSTRAINT FK_RC_CUISINE  FOREIGN KEY (CUISINE_ID)    REFERENCES CUISINES(CUISINE_ID)    ON DELETE CASCADE
);

-- =============================================================
-- TABLE: REVIEWS
-- =============================================================
CREATE TABLE REVIEWS (
  REVIEW_ID     NUMBER        DEFAULT SEQ_REVIEW_ID.NEXTVAL PRIMARY KEY,
  RESTAURANT_ID NUMBER        NOT NULL,
  USER_ID       NUMBER        NOT NULL,
  RATING        NUMBER(2,1)   NOT NULL,
  REVIEW_TEXT   VARCHAR2(2000), 
  CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP,
  CONSTRAINT UQ_REVIEW_USER_REST UNIQUE (RESTAURANT_ID, USER_ID),
  CONSTRAINT CHK_RATING          CHECK (RATING BETWEEN 1 AND 5),
  CONSTRAINT FK_REV_REST         FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS(RESTAURANT_ID) ON DELETE CASCADE,
  CONSTRAINT FK_REV_USER         FOREIGN KEY (USER_ID)       REFERENCES USERS(USER_ID)       ON DELETE CASCADE
);

COMMENT ON COLUMN REVIEWS.RATING IS 'Rating between 1.0 and 5.0';

-- =============================================================
-- TABLE: FAVORITES
-- =============================================================
CREATE TABLE FAVORITES (
  FAVORITE_ID   NUMBER    DEFAULT SEQ_FAVORITE_ID.NEXTVAL PRIMARY KEY,
  USER_ID       NUMBER    NOT NULL,
  RESTAURANT_ID NUMBER    NOT NULL,
  ADDED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT UQ_FAV_USER_REST UNIQUE (USER_ID, RESTAURANT_ID),
  CONSTRAINT FK_FAV_USER      FOREIGN KEY (USER_ID)       REFERENCES USERS(USER_ID)       ON DELETE CASCADE,
  CONSTRAINT FK_FAV_REST      FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS(RESTAURANT_ID) ON DELETE CASCADE
);

-- =============================================================
-- INDEXES for performance
-- =============================================================
CREATE INDEX IDX_REST_STATUS   ON RESTAURANTS(STATUS);
CREATE INDEX IDX_REST_LOCATION ON RESTAURANTS(LATITUDE, LONGITUDE);
CREATE INDEX IDX_REVIEWS_REST  ON REVIEWS(RESTAURANT_ID);
CREATE INDEX IDX_FAV_USER      ON FAVORITES(USER_ID);

-- =============================================================
-- TRIGGER: Auto-set IDs from sequence
-- =============================================================
CREATE OR REPLACE TRIGGER TRG_USERS_ID
BEFORE INSERT ON USERS
FOR EACH ROW
WHEN (NEW.USER_ID IS NULL)
BEGIN
  SELECT SEQ_USER_ID.NEXTVAL INTO :NEW.USER_ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_RESTAURANTS_ID
BEFORE INSERT ON RESTAURANTS
FOR EACH ROW
WHEN (NEW.RESTAURANT_ID IS NULL)
BEGIN
  SELECT SEQ_RESTAURANT_ID.NEXTVAL INTO :NEW.RESTAURANT_ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_REVIEWS_ID
BEFORE INSERT ON REVIEWS
FOR EACH ROW
WHEN (NEW.REVIEW_ID IS NULL)
BEGIN
  SELECT SEQ_REVIEW_ID.NEXTVAL INTO :NEW.REVIEW_ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_CUISINES_ID
BEFORE INSERT ON CUISINES
FOR EACH ROW
WHEN (NEW.CUISINE_ID IS NULL)
BEGIN
  SELECT SEQ_CUISINE_ID.NEXTVAL INTO :NEW.CUISINE_ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TRG_FAVORITES_ID
BEFORE INSERT ON FAVORITES
FOR EACH ROW
WHEN (NEW.FAVORITE_ID IS NULL)
BEGIN
  SELECT SEQ_FAVORITE_ID.NEXTVAL INTO :NEW.FAVORITE_ID FROM DUAL;
END;
/

-- =============================================================
-- SEED DATA
-- =============================================================

INSERT INTO USERS (USERNAME, EMAIL, PASSWORD_HASH, ROLE)
VALUES ('admin', 'admin@restaurant.com', 'sha256_hash_of_admin123', 'ADMIN');

INSERT INTO USERS (USERNAME, EMAIL, PASSWORD_HASH, ROLE)
VALUES ('john_doe', 'john@example.com', 'sha256_hash_of_password', 'USER');

INSERT INTO CUISINES (NAME) VALUES ('Indian');
INSERT INTO CUISINES (NAME) VALUES ('Chinese');
INSERT INTO CUISINES (NAME) VALUES ('Italian');
INSERT INTO CUISINES (NAME) VALUES ('Mexican');
INSERT INTO CUISINES (NAME) VALUES ('American');
INSERT INTO CUISINES (NAME) VALUES ('Japanese');
INSERT INTO CUISINES (NAME) VALUES ('Thai');
INSERT INTO CUISINES (NAME) VALUES ('Mediterranean');
INSERT INTO CUISINES (NAME) VALUES ('South Indian');
INSERT INTO CUISINES (NAME) VALUES ('Fast Food');

INSERT INTO RESTAURANTS (NAME, LATITUDE, LONGITUDE, ADDRESS, PRICE_RANGE, PHONE, STATUS, ADDED_BY)
VALUES ('Hotel RRR', 12.3052, 76.6554, 'Sayyaji Rao Rd, Mysuru, Karnataka 570001', '$$', '0821-2422700', 'APPROVED', 1);

INSERT INTO RESTAURANTS (NAME, LATITUDE, LONGITUDE, ADDRESS, PRICE_RANGE, PHONE, STATUS, ADDED_BY)
VALUES ('Mylari Hotel', 12.2958, 76.6394, 'Nazarbad, Mysuru, Karnataka 570010', '$', '0821-2344652', 'APPROVED', 1);

INSERT INTO RESTAURANTS (NAME, LATITUDE, LONGITUDE, ADDRESS, PRICE_RANGE, PHONE, STATUS, ADDED_BY)
VALUES ('The Old House', 12.3088, 76.6512, 'Nazarbad Main Road, Mysuru, Karnataka 570010', '$$$', '9876543210', 'APPROVED', 1);

INSERT INTO RESTAURANTS (NAME, LATITUDE, LONGITUDE, ADDRESS, PRICE_RANGE, STATUS, ADDED_BY)
VALUES ('Siddharta Hotel', 12.3177, 76.6536, 'Hotel Siddharta, 73/1 Guest House Road, Mysuru 570001', '$$', 'APPROVED', 1);

INSERT INTO RESTAURANTS (NAME, LATITUDE, LONGITUDE, ADDRESS, PRICE_RANGE, STATUS, ADDED_BY)
VALUES ('Vinayaka Mylari', 12.2987, 76.6321, 'Narayana Shastri Road, Mysuru, Karnataka 570001', '$', 'APPROVED', 1);

INSERT INTO RESTAURANT_CUISINE VALUES (1, 9); 
INSERT INTO RESTAURANT_CUISINE VALUES (2, 9); 
INSERT INTO RESTAURANT_CUISINE VALUES (3, 3); 
INSERT INTO RESTAURANT_CUISINE VALUES (4, 9); 
INSERT INTO RESTAURANT_CUISINE VALUES (5, 9); 

INSERT INTO REVIEWS (RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT)
VALUES (1, 2, 4.5, 'Great authentic South Indian food. The dosas are amazing!');

INSERT INTO REVIEWS (RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT)
VALUES (2, 2, 5.0, 'Best Mysore masala dosa in town. A must visit!');

COMMIT;

SELECT TABLE_NAME FROM USER_TABLES ORDER BY TABLE_NAME;