SET DEFINE OFF

-- =============================================================
-- SEED DATA: 20 Restaurants, Cuisines, 50+ Reviews
-- Run AFTER schema.sql
-- Coordinates are real Mysuru, Karnataka locations
-- =============================================================

-- Clear existing data (safe re-run)
DELETE FROM REVIEWS;
DELETE FROM FAVORITES;
DELETE FROM RESTAURANT_CUISINE;
DELETE FROM RESTAURANTS;
DELETE FROM CUISINES;
DELETE FROM USERS;

-- Reset sequences
DROP SEQUENCE SEQ_USER_ID;
DROP SEQUENCE SEQ_RESTAURANT_ID;
DROP SEQUENCE SEQ_REVIEW_ID;
DROP SEQUENCE SEQ_CUISINE_ID;
DROP SEQUENCE SEQ_FAVORITE_ID;

CREATE SEQUENCE SEQ_USER_ID       START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RESTAURANT_ID START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_REVIEW_ID     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CUISINE_ID    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_FAVORITE_ID   START WITH 1 INCREMENT BY 1 NOCACHE;

COMMIT;

-- =============================================================
-- USERS (admin + 10 reviewers)
-- =============================================================
INSERT INTO USERS (USER_ID, USERNAME, EMAIL, PASSWORD_HASH, ROLE)
VALUES (SEQ_USER_ID.NEXTVAL, 'admin',    'admin@restaurant.com',  'YWRtaW4xMjM=', 'ADMIN');

INSERT INTO USERS (USER_ID, USERNAME, EMAIL, PASSWORD_HASH, ROLE)
VALUES (SEQ_USER_ID.NEXTVAL, 'priya_m',  'priya@example.com',     'cGFzc3dvcmQ=', 'USER');

INSERT INTO USERS (USER_ID, USERNAME, EMAIL, PASSWORD_HASH, ROLE)
VALUES (SEQ_USER_ID.NEXTVAL, 'rahul_k',  'rahul@example.com',     'cGFzc3dvcmQ=', 'USER');

INSERT INTO USERS (USER_ID, USERNAME, EMAIL, PASSWORD_HASH, ROLE)
VALUES (SEQ_USER_ID.NEXTVAL, 'ananya_s', 'ananya@example.com',    'cGFzc3dvcmQ=', 'USER');

INSERT INTO USERS (USER_ID, USERNAME, EMAIL, PASSWORD_HASH, ROLE)
VALUES (SEQ_USER_ID.NEXTVAL, 'kiran_g',  'kiran@example.com',     'cGFzc3dvcmQ=', 'USER');

INSERT INTO USERS (USER_ID, USERNAME, EMAIL, PASSWORD_HASH, ROLE)
VALUES (SEQ_USER_ID.NEXTVAL, 'meera_v',  'meera@example.com',     'cGFzc3dvcmQ=', 'USER');

INSERT INTO USERS (USER_ID, USERNAME, EMAIL, PASSWORD_HASH, ROLE)
VALUES (SEQ_USER_ID.NEXTVAL, 'suresh_r', 'suresh@example.com',    'cGFzc3dvcmQ=', 'USER');

INSERT INTO USERS (USER_ID, USERNAME, EMAIL, PASSWORD_HASH, ROLE)
VALUES (SEQ_USER_ID.NEXTVAL, 'deepa_n',  'deepa@example.com',     'cGFzc3dvcmQ=', 'USER');

INSERT INTO USERS (USER_ID, USERNAME, EMAIL, PASSWORD_HASH, ROLE)
VALUES (SEQ_USER_ID.NEXTVAL, 'arjun_p',  'arjun@example.com',     'cGFzc3dvcmQ=', 'USER');

INSERT INTO USERS (USER_ID, USERNAME, EMAIL, PASSWORD_HASH, ROLE)
VALUES (SEQ_USER_ID.NEXTVAL, 'lakshmi_b','lakshmi@example.com',   'cGFzc3dvcmQ=', 'USER');

INSERT INTO USERS (USER_ID, USERNAME, EMAIL, PASSWORD_HASH, ROLE)
VALUES (SEQ_USER_ID.NEXTVAL, 'vijay_t',  'vijay@example.com',     'cGFzc3dvcmQ=', 'USER');

COMMIT;

-- =============================================================
-- CUISINES (5)
-- =============================================================
INSERT INTO CUISINES (CUISINE_ID, NAME) VALUES (SEQ_CUISINE_ID.NEXTVAL, 'South Indian');
INSERT INTO CUISINES (CUISINE_ID, NAME) VALUES (SEQ_CUISINE_ID.NEXTVAL, 'North Indian');
INSERT INTO CUISINES (CUISINE_ID, NAME) VALUES (SEQ_CUISINE_ID.NEXTVAL, 'Chinese');
INSERT INTO CUISINES (CUISINE_ID, NAME) VALUES (SEQ_CUISINE_ID.NEXTVAL, 'Fast Food');
INSERT INTO CUISINES (CUISINE_ID, NAME) VALUES (SEQ_CUISINE_ID.NEXTVAL, 'Bakery & Cafe');

COMMIT;

-- =============================================================
-- RESTAURANTS (20)
-- =============================================================
INSERT INTO RESTAURANTS (RESTAURANT_ID, NAME, LATITUDE, LONGITUDE, ADDRESS, PRICE_RANGE, PHONE, STATUS, ADDED_BY)
VALUES (SEQ_RESTAURANT_ID.NEXTVAL, 'Hotel RRR', 12.3052, 76.6554, 'Sayyaji Rao Rd, Mysuru 570001', '$$', '0821-2422700', 'APPROVED', 1);

INSERT INTO RESTAURANTS (RESTAURANT_ID, NAME, LATITUDE, LONGITUDE, ADDRESS, PRICE_RANGE, PHONE, STATUS, ADDED_BY)
VALUES (SEQ_RESTAURANT_ID.NEXTVAL, 'Mylari Hotel', 12.2958, 76.6394, 'Nazarbad, Mysuru 570010', '$', '0821-2344652', 'APPROVED', 1);

INSERT INTO RESTAURANTS (RESTAURANT_ID, NAME, LATITUDE, LONGITUDE, ADDRESS, PRICE_RANGE, PHONE, STATUS, ADDED_BY)
VALUES (SEQ_RESTAURANT_ID.NEXTVAL, 'Vinayaka Mylari', 12.3012, 76.6321, 'Narayana Shastri Rd, Mysuru 570001', '$', '0821-2441135', 'APPROVED', 1);

INSERT INTO RESTAURANTS (RESTAURANT_ID, NAME, LATITUDE, LONGITUDE, ADDRESS, PRICE_RANGE, PHONE, STATUS, ADDED_BY)
VALUES (SEQ_RESTAURANT_ID.NEXTVAL, 'Hotel Siddharta', 12.3177, 76.6536, 'Guest House Rd, Mysuru 570001', '$$', '0821-2422777', 'APPROVED', 1);

INSERT INTO RESTAURANTS (RESTAURANT_ID, NAME, LATITUDE, LONGITUDE, ADDRESS, PRICE_RANGE, PHONE, STATUS, ADDED_BY)
VALUES (SEQ_RESTAURANT_ID.NEXTVAL, 'Cafe Coffee Day - MG Road', 12.3086, 76.6551, 'MG Road, Mysuru 570001', '$$', '1800-123-3444', 'APPROVED', 1);

INSERT INTO RESTAURANTS (RESTAURANT_ID, NAME, LATITUDE, LONGITUDE, ADDRESS, PRICE_RANGE, PHONE, STATUS, ADDED_BY)
VALUES (SEQ_RESTAURANT_ID.NEXTVAL, 'Dominos Pizza - Nazarbad', 12.2989, 76.6406, 'Nazarbad Main Rd, Mysuru 570010', '$$', '0821-4000333', 'APPROVED', 1);

INSERT INTO RESTAURANTS (RESTAURANT_ID, NAME, LATITUDE, LONGITUDE, ADDRESS, PRICE_RANGE, PHONE, STATUS, ADDED_BY)
VALUES (SEQ_RESTAURANT_ID.NEXTVAL, 'The Rotary Club Lunch Home', 12.3135, 76.6498, 'Irwin Rd, Mysuru 570001', '$', NULL, 'APPROVED', 1);

INSERT INTO RESTAURANTS (RESTAURANT_ID, NAME, LATITUDE, LONGITUDE, ADDRESS, PRICE_RANGE, PHONE, STATUS, ADDED_BY)
VALUES (SEQ_RESTAURANT_ID.NEXTVAL, 'Chirag Restaurant', 12.3201, 76.6472, 'Dhanvantri Rd, Mysuru 570001', '$$', '0821-2423456', 'APPROVED', 1);

INSERT INTO RESTAURANTS (RESTAURANT_ID, NAME, LATITUDE, LONGITUDE, ADDRESS, PRICE_RANGE, PHONE, STATUS, ADDED_BY)
VALUES (SEQ_RESTAURANT_ID.NEXTVAL, 'Hanumanthu Military Hotel', 12.3067, 76.6589, 'Bamboo Bazaar, Mysuru 570001', '$', NULL, 'APPROVED', 1);

INSERT INTO RESTAURANTS (RESTAURANT_ID, NAME, LATITUDE, LONGITUDE, ADDRESS, PRICE_RANGE, PHONE, STATUS, ADDED_BY)
VALUES (SEQ_RESTAURANT_ID.NEXTVAL, 'Malgudi Restaurant', 12.2941, 76.6513, 'Vijayanagar, Mysuru 570017', '$$', '0821-2416789', 'APPROVED', 1);

INSERT INTO RESTAURANTS (RESTAURANT_ID, NAME, LATITUDE, LONGITUDE, ADDRESS, PRICE_RANGE, PHONE, STATUS, ADDED_BY)
VALUES (SEQ_RESTAURANT_ID.NEXTVAL, 'KFC - Forum Mall', 12.3012, 76.6445, 'Forum Mall, Mysuru 570016', '$$', '1800-103-2929', 'APPROVED', 1);

INSERT INTO RESTAURANTS (RESTAURANT_ID, NAME, LATITUDE, LONGITUDE, ADDRESS, PRICE_RANGE, PHONE, STATUS, ADDED_BY)
VALUES (SEQ_RESTAURANT_ID.NEXTVAL, 'Oyster Bay Restaurant', 12.3098, 76.6602, 'Lalitha Mahal Rd, Mysuru 570011', '$$$', '0821-2470777', 'APPROVED', 1);

INSERT INTO RESTAURANTS (RESTAURANT_ID, NAME, LATITUDE, LONGITUDE, ADDRESS, PRICE_RANGE, PHONE, STATUS, ADDED_BY)
VALUES (SEQ_RESTAURANT_ID.NEXTVAL, 'Hotel Dasaprakash', 12.3155, 76.6521, 'Gandhi Square, Mysuru 570001', '$$', '0821-2442444', 'APPROVED', 1);

INSERT INTO RESTAURANTS (RESTAURANT_ID, NAME, LATITUDE, LONGITUDE, ADDRESS, PRICE_RANGE, PHONE, STATUS, ADDED_BY)
VALUES (SEQ_RESTAURANT_ID.NEXTVAL, 'Bombay Tiffanys', 12.3022, 76.6378, 'Kuvempu Nagar, Mysuru 570023', '$', NULL, 'APPROVED', 1);

INSERT INTO RESTAURANTS (RESTAURANT_ID, NAME, LATITUDE, LONGITUDE, ADDRESS, PRICE_RANGE, PHONE, STATUS, ADDED_BY)
VALUES (SEQ_RESTAURANT_ID.NEXTVAL, 'Dynasty Chinese Restaurant', 12.3188, 76.6580, 'Nazarbad Mohalla, Mysuru 570010', '$$$', '0821-2434567', 'APPROVED', 1);

INSERT INTO RESTAURANTS (RESTAURANT_ID, NAME, LATITUDE, LONGITUDE, ADDRESS, PRICE_RANGE, PHONE, STATUS, ADDED_BY)
VALUES (SEQ_RESTAURANT_ID.NEXTVAL, 'Pizza Hut - Sayyaji Rao Rd', 12.3071, 76.6544, 'Sayyaji Rao Rd, Mysuru 570001', '$$', '0821-4000222', 'APPROVED', 1);

INSERT INTO RESTAURANTS (RESTAURANT_ID, NAME, LATITUDE, LONGITUDE, ADDRESS, PRICE_RANGE, PHONE, STATUS, ADDED_BY)
VALUES (SEQ_RESTAURANT_ID.NEXTVAL, 'Hotel Harsha', 12.2919, 76.6457, 'Vijayanagar 2nd Stage, Mysuru 570017', '$', NULL, 'APPROVED', 1);

INSERT INTO RESTAURANTS (RESTAURANT_ID, NAME, LATITUDE, LONGITUDE, ADDRESS, PRICE_RANGE, PHONE, STATUS, ADDED_BY)
VALUES (SEQ_RESTAURANT_ID.NEXTVAL, 'The Raj Restaurant', 12.3244, 76.6503, 'Vontikoppal, Mysuru 570002', '$$', '0821-2431234', 'APPROVED', 1);

INSERT INTO RESTAURANTS (RESTAURANT_ID, NAME, LATITUDE, LONGITUDE, ADDRESS, PRICE_RANGE, PHONE, STATUS, ADDED_BY)
VALUES (SEQ_RESTAURANT_ID.NEXTVAL, 'Bread and Butter Bakery', 12.3033, 76.6492, 'Lakshmipuram, Mysuru 570004', '$', NULL, 'APPROVED', 1);

INSERT INTO RESTAURANTS (RESTAURANT_ID, NAME, LATITUDE, LONGITUDE, ADDRESS, PRICE_RANGE, PHONE, STATUS, ADDED_BY)
VALUES (SEQ_RESTAURANT_ID.NEXTVAL, 'Cafe Aramane', 12.3119, 76.6567, 'Devaraja Mohalla, Mysuru 570001', '$$', '0821-2412345', 'APPROVED', 1);

COMMIT;

-- =============================================================
-- RESTAURANT_CUISINE links
-- =============================================================
INSERT INTO RESTAURANT_CUISINE VALUES (1, 1);
INSERT INTO RESTAURANT_CUISINE VALUES (2, 1);
INSERT INTO RESTAURANT_CUISINE VALUES (3, 1);
INSERT INTO RESTAURANT_CUISINE VALUES (4, 1);
INSERT INTO RESTAURANT_CUISINE VALUES (4, 2);
INSERT INTO RESTAURANT_CUISINE VALUES (7, 1);
INSERT INTO RESTAURANT_CUISINE VALUES (8, 2);
INSERT INTO RESTAURANT_CUISINE VALUES (8, 3);
INSERT INTO RESTAURANT_CUISINE VALUES (9, 1);
INSERT INTO RESTAURANT_CUISINE VALUES (10, 1);
INSERT INTO RESTAURANT_CUISINE VALUES (10, 2);
INSERT INTO RESTAURANT_CUISINE VALUES (12, 2);
INSERT INTO RESTAURANT_CUISINE VALUES (13, 1);
INSERT INTO RESTAURANT_CUISINE VALUES (13, 2);
INSERT INTO RESTAURANT_CUISINE VALUES (14, 1);
INSERT INTO RESTAURANT_CUISINE VALUES (17, 1);
INSERT INTO RESTAURANT_CUISINE VALUES (18, 2);
INSERT INTO RESTAURANT_CUISINE VALUES (20, 5);
INSERT INTO RESTAURANT_CUISINE VALUES (5, 5);
INSERT INTO RESTAURANT_CUISINE VALUES (6, 4);
INSERT INTO RESTAURANT_CUISINE VALUES (11, 4);
INSERT INTO RESTAURANT_CUISINE VALUES (16, 4);
INSERT INTO RESTAURANT_CUISINE VALUES (15, 3);
INSERT INTO RESTAURANT_CUISINE VALUES (19, 5);

COMMIT;

-- =============================================================
-- REVIEWS (55 total)
-- Note: USER_ID column quoted to avoid reserved word conflict
-- =============================================================

INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 1, 2, 5, 'Best thali in Mysuru, generous portions and great taste!');
INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 1, 3, 4, 'Authentic South Indian food, slightly slow service but worth it.');
INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 1, 4, 5, 'A Mysuru institution. Must-visit for dosa lovers.');

INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 2, 2, 5, 'The Mysore masala dosa here is unbeatable.');
INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 2, 5, 4, 'Crispy dosa, amazing coconut chutney. Go early or wait!');
INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 2, 6, 5, 'Legendary place. The butter dosa is heaven.');
INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 2, 7, 4, 'Classic. No frills, just excellent food.');

INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 3, 3, 4, 'Great idli and vada, worth the short wait.');
INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 3, 8, 5, 'Soft idlis, amazing sambar. One of the best!');
INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 3, 9, 3, 'Good food but very crowded during peak hours.');

INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 4, 2, 4, 'Nice ambiance, good variety of dishes.');
INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 4, 10, 3, 'Average food, but decent for a quick meal.');
INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 4, 11, 4, 'Solid North Indian and South Indian options.');

INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 5, 4, 3, 'Standard CCD. Good cold coffee, average snacks.');
INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 5, 5, 4, 'Nice spot to sit and work. WiFi is good.');
INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 5, 6, 3, 'Pricey for what you get but convenient location.');

INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 6, 3, 4, 'Fast delivery, pizza always hot and fresh.');
INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 6, 7, 3, 'Decent pizza. Gets very busy on weekends.');
INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 6, 8, 4, 'Great deals during lunch hour. Good value.');

INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 7, 9, 4, 'Excellent unlimited meals at a very low price.');
INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 7, 10, 5, 'Best value for money in Mysuru. Authentic home food.');
INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 7, 11, 4, 'Simple and wholesome. Packed at lunchtime.');

INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 8, 2, 3, 'Okay North Indian and Chinese mix. Nothing special.');
INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 8, 4, 4, 'The Chinese dishes are really good here!');
INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 8, 6, 3, 'Decent place but service can be slow.');

INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 9, 3, 5, 'Authentic Nati chicken here is absolutely amazing!');
INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 9, 5, 5, 'Best mutton curry in Mysuru. No doubt.');
INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 9, 7, 4, 'Spicy and flavorful. Great for meat lovers.');

INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 10, 8, 4, 'Good family restaurant, lots of variety.');
INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 10, 9, 3, 'Food is decent, portions could be bigger.');
INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 10, 11, 4, 'Nice place for a family dinner in Vijayanagar.');

INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 11, 2, 4, 'Standard KFC quality. Zinger burger is always good.');
INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 11, 6, 3, 'Bit pricey but kids love it. Clean seating area.');
INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 11, 10, 4, 'Great for a quick meal at the mall.');

INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 12, 3, 5, 'Fine dining experience. The buffet spread is excellent.');
INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 12, 4, 4, 'Great for special occasions. Food is top class.');
INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 12, 5, 5, 'Luxurious ambiance, impeccable service.');

INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 13, 7, 4, 'Iconic Mysuru restaurant. Pure veg and very tasty.');
INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 13, 8, 5, 'Their Mysore pak and filter coffee are legendary.');
INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 13, 9, 4, 'Good heritage feel. Consistent quality.');

INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 14, 10, 4, 'Great budget breakfast spot. Poha and upma are top notch.');
INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 14, 11, 3, 'Limited menu but what they make is good.');

INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 15, 2, 4, 'Best Chinese food in Mysuru. Manchurian is amazing!');
INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 15, 3, 5, 'Authentic Chinese flavours. Fried rice is excellent.');
INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 15, 6, 4, 'Good portions and value for a premium restaurant.');

INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 16, 4, 3, 'Standard Pizza Hut. Pasta is better than the pizza.');
INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 16, 7, 4, 'Good for a family outing. Kids loved the desserts.');

INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 17, 5, 4, 'Hidden gem in Vijayanagar. Very affordable thali.');
INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 17, 8, 3, 'Nothing fancy but clean and filling food.');
INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 17, 11, 4, 'Great local spot, regulars know the value here.');

INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 18, 9, 4, 'Good butter chicken and naan. Family friendly.');
INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 18, 10, 3, 'Decent North Indian but slightly overpriced.');

INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 19, 2, 5, 'Freshest bread in Mysuru. The croissants are divine!');
INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 19, 11, 4, 'Great cakes and pastries. Perfect for takeaway.');

INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 20, 3, 4, 'Cozy cafe with great filter coffee and snacks.');
INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 20, 4, 5, 'Lovely ambiance, great for a relaxed evening.');
INSERT INTO REVIEWS (REVIEW_ID, RESTAURANT_ID, USER_ID, RATING, REVIEW_TEXT) VALUES (SEQ_REVIEW_ID.NEXTVAL, 20, 5, 4, 'Excellent filter coffee and South Indian snacks.');

COMMIT;

-- Verify counts
SELECT 'USERS'       AS TBL, COUNT(*) AS CNT FROM USERS
UNION ALL SELECT 'RESTAURANTS', COUNT(*) FROM RESTAURANTS
UNION ALL SELECT 'CUISINES',    COUNT(*) FROM CUISINES
UNION ALL SELECT 'RC_LINKS',    COUNT(*) FROM RESTAURANT_CUISINE
UNION ALL SELECT 'REVIEWS',     COUNT(*) FROM REVIEWS;